// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Smaple01.DBContexts;

#nullable disable

namespace Smaple01.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    [Migration("20251201161253_dataseed")]
    partial class dataseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Smaple01.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "best place to live in",
                            Name = "NewYork"
                        },
                        new
                        {
                            Id = 2,
                            Description = "always rainy",
                            Name = "London"
                        },
                        new
                        {
                            Id = 3,
                            Description = "most romance city",
                            Name = "Paris"
                        });
                });

            modelBuilder.Entity("Smaple01.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("pointOfInterests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "gourgeos",
                            Name = "FreedomStatus"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "clean",
                            Name = "Parks"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "big",
                            Name = "Clock"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "red",
                            Name = "PhoneStations"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Description = "Wonderful",
                            Name = "Eiffel"
                        });
                });

            modelBuilder.Entity("Smaple01.Entities.PointOfInterest", b =>
                {
                    b.HasOne("Smaple01.Entities.City", "City")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Smaple01.Entities.City", b =>
                {
                    b.Navigation("PointsOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
